### ISSUE TITLE
Telemarketing-Sales Repository

### ISSUE THREAD

**Issue by johncarlostacruz** [mtcuison/Telemarketing-Sales#2]
**ENTRY/Approval**
- [x] Save the transaction - pag sinave may lumalabas na message box.
![image](https://github.com/mtcuison/Telemarketing-Sales/assets/23698764/74eecd83-53aa-4dac-8f7f-86a3a372c4c1)

- [x] Only accounts with supervisor or above user level can approve a transaction - lumabas yung save message pero walang masearch sa approval.
![image](https://github.com/mtcuison/Telemarketing-Sales/assets/23698764/d9007c1c-4523-4998-a662-6c5b8a60859e)

**Comment by mtcuison** [comment]
hindi ko mabasa yung message parekoy. pakitaasan mo yung resolution. sa history ang lalabas lang yung approved or cancelled. pag open pa, doon pa sa entry/approval form lalabas.

**Comment by mtcuison** [comment]
good pm parekoy. pakikuha mo yung update sa \\192.168.10.15\share\TLM 20230815.zip

tas try mo ulit.

thanks.

**Comment by johncarlostacruz** [comment]
**ENTRY**
>request nila na kung pwede maupdate nila yung remarks..

**Comment by mtcuison** [comment]
> **ENTRY**
> 
> > request nila na kung pwede maupdate nila yung remarks..

will re-create issue for this.
